version: '2'

services:

  app:
    image: php:5.6-apache
    volumes:
      - ./:/var/www/html
    links:
      - db
    ports:
      - "80:80"

  db:
    image: mysql:5.7
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_USER=ssas
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=root

volumes:
  mysql:
    driver: "local"
