version: '2'

services:

    app:
        build:
            context: ./
            args:
                - INSTALL_GD=true
                - INSTALL_ZIP_ARCHIVE=true
            dockerfile: Dockerfile-56
        volumes:
            - ./app:/var/www/html
        ports:
           - "80:80"

#    db:
#        image: mariadb
#        volumes:
#            - mysql:/var/lib/mysql
#    ports:
#      - "3306:3306"
#    environment:
#      - MYSQL_DATABASE=app
#      - MYSQL_USER=ssas
#      - MYSQL_PASSWORD=secret
#      - MYSQL_ROOT_PASSWORD=root
#
#volumes:
#    mysql:
#        driver: "local"